### ISSUE TITLE
Remove all StateReceivers on CoroutineScope close

### ISSUE THREAD

**Issue by Tapchicoma** [freeletics/CoRedux#34]
This will reduce the possibility of memory leaks.

**Comment by sockeqwe** [comment]
But that raises another question: how would a subscriber (StateReceiver) know that the store has been closed?

I think the real problem is multiple subscribers. One could also say cold observable alike channels could solve this problem. Hence we could also just allow one single subscriber and leave it to the developers using CoRedux to decide how to "broadcast" the new state from the single StateReceiver to other components interested in the state.

Btw. this could be an interesting "learning" for your next kotlin meetup talk ...

**Comment by Tapchicoma** [comment]
> But that raises another question: how would a subscriber (StateReceiver) know that the store has been closed?

I would this needs discussion - `CoroutineScope` is controlled outside of the `Store` and can be checked directly, before calling `subscribe()`. In the case, when `StateReceiver` doesn't have access to `CoroutineScope` - it can use `try { .. } catch(e: IllegalStateException) { .. }` to get the state (see opened PR).

**Comment by sockeqwe** [comment]
Maybe we should add a `StateReceiver.onStoreClosed()` callback to `StateReceiver` to avoid the scenario that store gets closed but `StateReceiver` waits forever for next state because `StateReceiver` doesn't know that store has been closed ...
